apiVersion: v1
kind: Pod
metadata:
  labels:
    app: webapp
    release: "0"
  name: webapp-pod
spec:
  containers:
    - image: richardchesterwood/k8s-fleetman-webapp-angular:release0
      name: webapp
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: webapp
    release: "0-5"
  name: webapp-pod-2
spec:
  containers:
    - image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
      name: webapp