apiVersion: v1
kind: Pod
metadata:
  name: queue-pod
  labels:
    app: queue
spec:
  containers:
    - name: queue-container
      image:  richardchesterwood/k8s-fleetman-queue:release1
---
apiVersion: v1
kind: Service
metadata: 
  name: queue-service
spec: 
  selector:
    app: queue
  type: NodePort
  ports:
  - name:  http
    port:  8161
    nodePort: 30010